name: Clean releases

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  clean-releases:
    if: github.repository == 'ROCKNIX/distribution-nightly'
    runs-on: ubuntu-latest
    steps:
      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 5
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 10
          gh_token: ${{ secrets.GITHUB_TOKEN }}