name: Build

on: [workflow_dispatch]

jobs:

  build-nightly:
    uses: tiopex/distribution/.github/workflows/build-nightly.yml@dev
    with:
      submodule: distribution

  release-nightly:
    runs-on: ubuntu-latest
    needs: build-nightly
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ROCKNIX-nightly-*
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ROCKNIX-nightly-*