name: Build

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
jobs:
  build-nightly:
    if: startsWith(github.ref, 'refs/tags/')
    uses: tiopex/distribution/.github/workflows/build-nightly.yml@dev
    with:
      submodule: distribution

  release-nightly:
    runs-on: ubuntu-latest
    needs: build-nightly
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ROCKNIX-nightly-*
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ROCKNIX-*
      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 5
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 10
          gh_token: ${{ secrets.GITHUB_TOKEN }}