name: Build

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
jobs:
  build-nightly:
#    if: startsWith(github.ref, 'refs/tags/')
#    uses: tiopex/distribution/.github/workflows/build-nightly.yml@dev
#    with:
#      submodule: distribution
    runs-on: ubuntu-latest
    steps:
      - name: retrieve ccache aarch64-toolchain
        id: retrieve-cache
        uses: actions/cache/restore@v4
        with:
          path: test
          key: ccache-${{ github.sha }}
          restore-keys: |
            ccache-${{ github.sha }}
            ccache-
      - name: test build
        run: |
          mkdir -p test
          echo "test" > test/test.txt
      - name: save ccache
        if: ${{ ! steps.retrieve-cache.outputs.cache-hit || steps.retrieve-cache.outputs.cache-matched-key != env.CACHE_KEY }}
        uses: actions/cache/save@v4
        with:
          path: test
          key: ccache-${{ github.sha }}
      - name: get date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.DATE }}
          commit: main
          artifacts: "test/*.txt"
          allowUpdates: true
          makeLatest: true


#  release-nightly:
#    runs-on: ubuntu-latest
#    needs: build-nightly
#    steps:
#      - name: Download artifacts
#        uses: actions/download-artifact@v4
#        with:
#          pattern: ROCKNIX-nightly-*
#          merge-multiple: true
#      - name: Release
#        uses: softprops/action-gh-release@v2
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: ROCKNIX-*
#      - name: Delete releases and workflows runs
#        uses: ophub/delete-releases-workflows@main
#        with:
#          delete_releases: true
#          releases_keep_latest: 5
#          delete_tags: true
#          delete_workflows: true
#          workflows_keep_day: 10
#          gh_token: ${{ secrets.GITHUB_TOKEN }}